# Simulator Global Settings
simulator:
  world_rate: 1000 # Hz
  control_rate: 100 # Hz
  sim_time: 20 # seconds

  additional_sensors:
    imu_1:
      type: "imu"
      noise_mean: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      noise_stddev: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # Event camera is more of an accumulation rate.
  # That is events are generated at world rate and
  # only displayed at this rate
  sensor_rates:
    imu_1: 50 # Hz
    event_camera_1: 20 # Hz
    color_camera_1: 10 # Hz
    depth_camera_1: 10 # Hz
    navmesh_1: 10 # Hz

# Visual Backend Settings
visual_backend:
  gpu_id: 0
  scene: "data/scene_datasets/habitat-test-scenes/apartment_1.glb"
  scene_dataset_config_file: "default"
  clear_color: [0.0, 0.0, 0.0, 1.0] # BLACK in RGBA (assuming mn.Color4.from_linear_rgb_int(0))
  default_agent: 0

  # Add agent dimensions from the vehicle model if needed

  # default_agent_navmesh: true
  # navmesh_include_static_objects: false
  enable_hbao: false
  frustum_culling: true

  seed: 324
  physics_config_file: "data/default.physics_config.json"
  enable_physics: true # Replace with false if `built_with_bullet` is False

  sensors:
    event_camera_1:
      type: "event"
      position: [0.0, 0.0, 0.05]
      orientation: [0.0, 0.0, 0.0, 1.0]
      width: 640
      height: 480
      hfov: 90
      zfar: 10.0
      backend: "cuda"
      contrast_threshold_neg: 0.35
      contrast_threshold_pos: 0.35

    color_camera_1:
      name: "color_camera_1"
      type: "color"
      position: [0.0, 0.0, 0.05]
      orientation: [0.0, 0.0, 0.0, 1.0]
      width: 640
      height: 480
      hfov: 90
      zfar: 10.0

    depth_camera_1:
      type: "depth"
      position: [0.0, 0.0, 0.05]
      orientation: [0.0, 0.0, 0.0, 1.0]
      width: 640
      height: 480
      hfov: 90
      zfar: 10.0

# Controller settings
controller:
  model: "rotorpy_se3"
  vehicle: "crazyflie"

# Dynamics settings
dynamics:
  model: "rotorpy_multirotor_euler"
  vehicle: "crazyflie"

# Trajectory settings
start_position: [0, -3, 0.2]
start_orientation: [0, 0, 0, 1] # Quaternion [x, y, z, w]
trajectory:
  model: "polynomial"
  points: [[0, -3, 0.2], [0, 1, 0.2], [4, 1, 0.2], [4, -1.5, 0.2]]
  v_avg: 1
